In [8]:
#pip install pandas

In [2]:
import pandas as pd

In [15]:
#print the data in two forms->Series and DataFrame
#Series->it will print in a series, start from '0'
a=[10,20,30,40,50]
pd.Series(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
b=[2.3,4.5,3.4,6.7]
pd.Series(b)

0    2.3
1    4.5
2    3.4
3    6.7
dtype: float64

In [11]:
c=["python","java","c++"]
pd.Series(c)

0    python
1      java
2       c++
dtype: str

In [12]:
d=[8+5j,5+4j,3+9j]
pd.Series(d)

0    8.0+5.0j
1    5.0+4.0j
2    3.0+9.0j
dtype: complex128

In [21]:
e=[True,False]
pd.Series(e)

0     True
1    False
dtype: bool

In [26]:
#DataFrame->Multiple columns with row indices
a={"names":["kavya","suma","anjali"],"marks":[60,70,80]}
pd.DataFrame(a)

    names  marks
0   kavya     60
1    suma     70
2  anjali     80

In [29]:
b={"names":["poojitha","chaitra","tara"],"subjects":["Maths","python","java"],"marks":[50,60,70]}
pd.DataFrame(b)

      names subjects  marks
0  poojitha    Maths     50
1   chaitra   python     60
2      tara     java     70

In [33]:
#reading and printing the external csv file that csv file should be within the folder
data=pd.read_csv("dataset.csv")
data

        Name  Marks
0   Poojitha     80
1  Varshitha     90
2    Chaitra     40
3       Tara     60
4       Maya     50
5      Priya     75
6      Sreya     86

In [37]:
#print columns
data.columns

Index(['Name', 'Marks'], dtype='str')

In [38]:
#prints rows and columns
data.shape

(7, 2)

In [39]:
#prints all information
data.info

<bound method DataFrame.info of         Name  Marks
0   Poojitha     80
1  Varshitha     90
2    Chaitra     40
3       Tara     60
4       Maya     50
5      Priya     75
6      Sreya     86>

In [46]:
d=pd.read_csv("worldcup.csv")
d

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,0.0,41.9,27.7,31.3,40.5,1,0,97,0,0.0
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,0.0,64.2,53.1,64.8,64.3,2,0,206,0,0.0
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,0.0,75.4,55.0,65.0,64.5,1,1,359,0,0.0
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,0.0,96.3,39.6,99.0,99.0,0,0,342,0,0.0
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,0.0,99.0,34.1,99.0,99.0,0,0,286,0,0.0

In [47]:
d.columns

Index(['player_id', 'player_name', 'age', 'nationality', 'team',
       'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot',
       'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium',
       'city', 'opponent_team', 'tournament_stage', 'match_result',
       'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists',
       'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa',
       'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy',
       'dribbles_attempted', 'successful_dribbles', 'crosses',
       'successful_crosses', 'tackles', 'interceptions', 'clearances',
       'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries',
       'defensive_actions', 'fouls_committed', 'fouls_suffered',
       'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage',
       'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves',
       'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh',
       'accelerations', 'decelerations', 'stamina_score', 'player_rating',
       'performance_score', 'offensive_contribution', 'defensive_contribution',
       'possession_impact', 'pressure_resistance', 'creativity_score',
       'consistency_score', 'clutch_performance_score',
       'total_goals_tournament', 'total_assists_tournament',
       'total_minutes_tournament', 'player_of_match_awards',
       'tournament_rating'],
      dtype='str')

In [48]:
d.shape

(54600, 75)

In [49]:
d.info

<bound method DataFrame.info of       player_id       player_name  age nationality   team  jersey_number  \
0        P00055        Rodri Fati   26     Spanish  Spain              3
1        P00070   Ansu Le Normand   19     Spanish  Spain             18
2        P00066        Gavi Ramos   18     Spanish  Spain             14
3        P00073     Pedro Cubarsi   20     Spanish  Spain             21
4        P00059  Alvaro Oyarzabal   23     Spanish  Spain              7
...         ...               ...  ...         ...    ...            ...
54595    P00996       Amir Younis   28       Iraqi   Iraq              8
54596    P01006  Safaa Al-Khafaji   20       Iraqi   Iraq             18
54597    P01008     Ahmed Hussein   26       Iraqi   Iraq             20
54598    P00991     Ibrahim Mhawi   30       Iraqi   Iraq              3
54599    P00989  Mohannad Hussein   27       Iraqi   Iraq              1

         position  height_cm  weight_kg preferred_foot  ... possession_impact  \
0      Goalkeeper        195         75           Left  ...               1.1
1      Midfielder        178         75          Right  ...               3.5
2      Midfielder        177         72           Left  ...              15.3
3         Forward        182         74          Right  ...               1.2
4        Defender        191         81           Left  ...               6.2
...           ...        ...        ...            ...  ...               ...
54595    Defender        177         73          Right  ...               0.0
54596  Midfielder        176         72          Right  ...               0.0
54597  Midfielder        173         77           Left  ...               0.0
54598  Goalkeeper        190         81          Right  ...               0.0
54599  Goalkeeper        187         73          Right  ...               0.0

       pressure_resistance creativity_score consistency_score  \
0                     44.2             55.9              42.0
1                     38.2             43.7              31.1
2                     99.0             99.0              83.4
3                     19.8             42.3              40.9
4                     44.1             33.5              60.0
...                    ...              ...               ...
54595                 41.9             27.7              31.3
54596                 64.2             53.1              64.8
54597                 75.4             55.0              65.0
54598                 96.3             39.6              99.0
54599                 99.0             34.1              99.0

      clutch_performance_score total_goals_tournament  \
0                         51.8                      0
1                         52.7                      0
2                         54.8                      1
3                         78.5                      5
4                         56.6                      0
...                        ...                    ...
54595                     40.5                      1
54596                     64.3                      2
54597                     64.5                      1
54598                     99.0                      0
54599                     99.0                      0

      total_assists_tournament total_minutes_tournament  \
0                            0                      242
1                            3                      342
2                            1                      245
3                            3                      422
4                            0                      440
...                        ...                      ...
54595                        0                       97
54596                        0                      206
54597                        1                      359
54598                        0                      342
54599                        0                      286

      player_of_match_awards  tournament_rating
0                          0                5.8
1                          0                5.5
2                          0                8.4
3                          0                6.7
4                          0                5.7
...                      ...                ...
54595                      0                0.0
54596                      0                0.0
54597                      0                0.0
54598                      0                0.0
54599                      0                0.0

[54600 rows x 75 columns]>